apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-app
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
        - name: counter-app
          image: avaleror/susecon23-demo:latest
          ports:
            - containerPort: 4000
          env:
            - name: PHX_HOST
              value: "127.0.0.1"
              #value: $(KUBERNETES_SERVICE_HOST)
              #value: $(COUNTER-APP_SERVICE_HOST)
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: counter-app-secret
                  key: key

