apiVersion: v1
kind: Service
metadata:
  name: counter-app
spec:
  selector:
    app: counter-app
  ports:
    - protocol: TCP
      port: 4000
      #port: 80
      targetPort: 4000
  type: ClusterIP

